### ISSUE TITLE
Cannot connect via USB immediately after plugging in

### ISSUE THREAD

**Issue by Ho-Ro** [DiSlord/NanoVNA-D#11]
**Issue:** Cannot connect via USB immediately after plugging in.
To check this: Connect to USB., switch on and type after one to two seconds:
````minicom -D /dev/ttyACM0````
It will fail in most cases:
````minicom: cannot open /dev/ttyACM0: Device or resource busy````

**System:** Linux debian stable

**Reason:** The NanoVNA announces itself as a CDC device (linux port e.g. /dev/ttyACM0) with bInterfaceProtocol = 0x01. According to *Universal Serial Bus Class Definitions for Communications Devices* section 4.4 this is
`01h ITU-T  V.250   AT Commands: V.250 etc`
Due to this announcement as a modem with AT commands some background processes are triggered (ModemManager?) that grab this *"modem"* and delay the availability of the device. 
The correct interface protocol is:
````00h  USB specification  No class specific protocol required````

**Fix:** Change entry in usbcfg.c:
````
@@ -68,11 +68,11 @@ static const uint8_t vcom_configuration_descriptor_data[67] = {
                          0x02,          /* bInterfaceClass (Communications
                                            Interface Class, CDC section
                                            4.2).                            */
                          0x02,          /* bInterfaceSubClass (Abstract
                                          Control Model, CDC section 4.3).   */
-                         0x01,          /* bInterfaceProtocol (AT commands,
+                         0x00,          /* bInterfaceProtocol (No protocol,
                                            CDC section 4.4).                */
                          0),            /* iInterface.                      */
   /* Header Functional Descriptor (CDC section 5.2.3).*/
   USB_DESC_BYTE         (5),            /* bLength.                         */
   USB_DESC_BYTE         (0x24),         /* bDescriptorType (CS_INTERFACE).  */
````

**Comment by DiSlord** [comment]
Thanks, soon add this fix
