### ISSUE TITLE
NanoVnaApp link broken on readme

### ISSUE THREAD

**Issue by delight-f** [DiSlord/NanoVNA-D#12]

**Comment by nlroth** [comment]
Please don't open an issue without actually describing the problem and/or helping to fix it.
If you tried to go back by one directory level, you'd see it's a RAR file.
https://github.com/OneOfEleven/NanoVNA-H/tree/master/Release

**Comment by delight-f** [comment]
The problem didn't really need any further description in the body, did it? The title said it all. 
--
Sent from myMail for Android Tuesday, 22 June 2021, 09:54pm +10:00 from nlroth  ***@***.*** :
