### ISSUE TITLE
Change scale - display issue 

### ISSUE THREAD

**Issue by delight-f** [DiSlord/NanoVNA-D#19]
When you try to change the scale for a trace, the buttons are not visible to select the unit. This is on a nanovna h v3.4 running latest dislord firmware.

[Screenshot](https://i.ibb.co/Vxq5sDT/MVIMG-20210820-102405.jpg)

**Comment by DiSlord** [comment]
For scale possible add only x1 multiplier value, so if need add for example 1kOm for one cell, need input 1000 and x1
Need input 10dB need input 10 and x1
Why need units in input?
