### ISSUE TITLE
build issue on Mac

### ISSUE THREAD

**Issue by n3xus1** [DiSlord/NanoVNA-D#22]
I get the following build error on Mac

`main.c:1093:10: fatal error: vna_modules/vna_renorm.c: No such file or directory
 #include "vna_modules/vna_renorm.c"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
`

**Comment by DiSlord** [comment]
Fixed in
https://github.com/DiSlord/NanoVNA-D/commit/38ddfe14191476982ec31b2bdb6a396a855b6ab8
This option disabled
