### ISSUE TITLE
NanoVNA Firmware version 1.1.00 - Incomplete menu image 

### ISSUE THREAD

**Issue by oridolfi** [DiSlord/NanoVNA-D#27]
I have just updated my device and found that the Display -> Scale -> Scale/Div and Reference Position menus are not being displayed properly. The right/upper corner of the image shows previous menus images and as result, some buttons for this settings are missing.

Hope this feedback helps to improve your astonishing software.

Best regards
Oscar

**Comment by OneOfEleven** [comment]
Surprised to see DiSlord making any posts at all with the psychotic 'P' doing it's thing. Hope you're safe.

**Comment by DiSlord** [comment]
Not understand problem, but look like Scale/Ref button not draw? You use SD card? If yes remove it from device

**Comment by oridolfi** [comment]
I menat to say that upper-Right buttons on the Scale/Div and Reference windows are not drawn.  Instead, part of the previous windows is shown in that place (upper-right).  please,see the both screens' attached pictures.
I'm using NanoVNA Firmware version 1.1.00 

![Reference Position](https://user-images.githubusercontent.com/69212034/160306580-f22b5df8-bc2f-477e-8610-c15a9cb8721c.jpg)
![Scale-Div](https://user-images.githubusercontent.com/69212034/160306582-393d5c68-ba78-4164-b9e6-3f2f1d821466.jpg)

Hope this clarifies.
Thanks.

**Comment by oridolfi** [comment]
To complement my previous post.
This is the dfu file I downloaded: (https://github.com/DiSlord/NanoVNA-D/releases/download/v1.1.00/NanoVNA.H.v1.1.00.dfu)
No SD in use.

**Comment by nlroth** [comment]
There is no problem. You're in a keyboard numerical entry mode so only the keyboard is shown until you enter a number and press return or just enter the back key with no entry. Either will cause the keyboard to clear the screen and you'll be back to where you were with fully functioning menus. 
 
 
  On Sun., 27 Mar. 2022 at 7:53 p.m., ***@***.***> wrote:   


I menat to say that upper-Right buttons on the Scale/Div and Reference windows are not drawn. Instead, part of the previous windows is shown in that place (upper-right). please,see the both screens' attached pictures.
I'm using NanoVNA Firmware version 1.1.00




Hope this clarifies.
Thanks.

**Comment by DiSlord** [comment]
Yes keyboard draw under menu, for this keyboard no buttons at this place
