### ISSUE TITLE
USB enumeration

### ISSUE THREAD

**Issue by owenduffy** [DiSlord/NanoVNA-D#28]
It appears that two devices with v1.1.0 firmware cannot both obtain a COM port on Win10, the first one attached does and the second one seems not the enumerate fully and produce a COM port. I note they both have the same VID,PID (to be expected) and SERIAL which may be the root cause of this problem.

Is it feasible to have each new installed firmware create a random serial number which it retains for future use. Perhaps if it recognised the factory serial no, it replaces it with a random value which it uses on later starts.

Owen

**Comment by owenduffy** [comment]
... or perhaps there is a unique id available from the ST parts?

**Comment by DiSlord** [comment]
Strange i can use H and H4 device on my Windows 7
![image](https://user-images.githubusercontent.com/28828/163708597-534901e1-418d-4bc9-beab-b0a2da58ec4e.png)
COM10 NanoVNA H
![image](https://user-images.githubusercontent.com/28828/163708627-1fa6b873-cf6f-4d19-b104-f178bb02a992.png)
COM29 NanoVNA H4
![image](https://user-images.githubusercontent.com/28828/163708651-3a157351-3db1-4511-ac23-2f225403a059.png)

**Comment by owenduffy** [comment]
Hi,
I repeated the test, and it is working fine. One of them comes with with serial 400, the next one has a blank serial and enumerates properly getting a com port. I tried this several times a few days ago and it consistently failed... perhaps a reboot has cleaned stuff up. Sorry for the false start.
