### ISSUE TITLE
build error on v1.2.01

### ISSUE THREAD

**Issue by Ho-Ro** [DiSlord/NanoVNA-D#29]
Hi DiSlord, trying to build the latest version from GitHub gives this error:
```
ui.c: In function 'ui_mode_normal':
ui.c:2974:42: error: 'UI_BROWSER' undeclared (first use in this function)
   if (ui_mode == UI_KEYPAD || ui_mode == UI_BROWSER)
                                          ^~~~~~~~~~
ui.c:2974:42: note: each undeclared identifier is reported only once for each function it appears in
```

I commented the use of SD card: `// #define __USE_SD_CARD__`, this should disable the use of `UI_BROWSER` in ui.c, but the `#ifdef ...` is missing in [line 2974](https://github.com/DiSlord/NanoVNA-D/blob/d67741f6eac869f3a9f2f882292353ebe92d4f68/ui.c#L2974):
```
  if (ui_mode == UI_KEYPAD || ui_mode == UI_BROWSER)
```

My fix:
```
#ifdef __SD_FILE_BROWSER__
  if (ui_mode == UI_KEYPAD || ui_mode == UI_BROWSER)
#else
  if (ui_mode == UI_KEYPAD )
#endif
```

**Comment by DiSlord** [comment]
Fix this error in
https://github.com/DiSlord/NanoVNA-D/commit/7121d1ffc2ad90ee3335029f97237f6cedca6a93
