### ISSUE TITLE
Make Fails

### ISSUE THREAD

**Issue by KE0ZUW** [DiSlord/NanoVNA-D#3]
The dfu-util -d 0483:df11 -a 0 -s 0x08000000:leave -D build/ch.bin

fails with no ch.bin in the build directory.

I believe it is an error during the make  process

Thank You   John

**Comment by galileo-pkm** [comment]
ch.bin is a product of the build, run make and if the build is successful you will get ch.bin in the build folder.

**Comment by KE0ZUW** [comment]
That is my point.  I run make and the file ch.bin is not there.

John

**Comment by galileo-pkm** [comment]
And the make was successful?

**Comment by KE0ZUW** [comment]
It fails with an error.  I will run it again tomorrow and post it!

JN

**Comment by DiSlord** [comment]
See this https://github.com/DiSlord/NanoVNA-D/issues/1#issuecomment-698945620
