### ISSUE TITLE
Message "too many arguments, max 4" disturbs NanoVNASaver.

### ISSUE THREAD

**Issue by Ho-Ro** [DiSlord/NanoVNA-D#34]
Why do I get this response when I simple press `ENTER`? 
```
too many arguments, max 4
```
It comes from [`main.c`](https://github.com/DiSlord/NanoVNA-D/blob/master/main.c#L3172-#L3175).

Programs like e.g. NanoVNASaver don't like this response:
```
2022-07-14 17:55:45,857 - NanoVNASaver.Hardware.Hardware - ERROR - No VNA detected. Hardware responded to CR with: 
too many arguments, max 4
ch> 
```
My quick fix is to comment the `shell_printf` line 3173.

**Comment by DiSlord** [comment]
Must be fixed in last commit

**Comment by Ho-Ro** [comment]
ok, thx
