### ISSUE TITLE
doc: Please add `dfu-util` cmd in README.md for Linux users

### ISSUE THREAD

**Issue by KJ7NLL** [DiSlord/NanoVNA-D#35]
Hello, this is how we flashed a DFU from Linux but I had to search around google a bit to find it.  Can you add this to your README.md file?:
```
dfu-util  -a 0 -D NanoVNA.H.v1.2.00.dfu
```

BTW, the new virmware works great!  Its like I have a brand-new VNA!

**Comment by Ho-Ro** [comment]
If you build your own binary then you can easily call `make flash` from the project directory, this issues the command `dfu-util -d 0483:df11 -a 0 -s 0x08000000:leave -D build/ch.bin`.
