### ISSUE TITLE
Confused about what version my NanoVNA is, and the README.md doesn't help....

### ISSUE THREAD

**Issue by frohro** [DiSlord/NanoVNA-D#39]
When I go to Config->Version it says NanoVNA at the top, but It has this website listed as the source of the firmware, which is 1.0.64.  I read that the H version is the 2.8" display which I have, but I also read the original NanoVNA is not supported anymore.  Will I brick my unit if I try and load the version 1.2?  Maybe this could be made more clear somewhere on this repository.
Thanks!
Rob

**Comment by Ho-Ro** [comment]
> I also read the original NanoVNA is not supported anymore

Where? On top right of the page I read this
![image](https://user-images.githubusercontent.com/12542359/191759468-b10c0ca2-1865-4be1-93b2-e5cc0a60638c.png)
