### ISSUE TITLE
Artefacts when capturing the screen

### ISSUE THREAD

**Issue by Ho-Ro** [DiSlord/NanoVNA-D#41]
The screen capture shows artefacts at the bottom of the image in the far right column. This is independent of the respective device and the recording program used; tinySA also shows the same artefacts. NanoVNA version 1.2.15, the issue existed also with versions 1.0.64 and 1.1.x, also latest tinySA version. 

see also https://github.com/erikkaashoek/tinySA/issues/36

![NanoVNA_capture_artefact](https://user-images.githubusercontent.com/12542359/201532715-67d55e3a-d10c-4adb-a04f-348db359bd4b.png) ![image](https://user-images.githubusercontent.com/12542359/201532889-c1174cad-e7f4-4013-a087-be565477bb50.png)

![tinySA_capture_artefact](https://user-images.githubusercontent.com/12542359/201532719-88cb81fa-33bd-4d3f-ae24-05d6fb372060.png) ![image](https://user-images.githubusercontent.com/12542359/201532955-e658df67-b539-48bb-a8d6-8ad567aae237.png)

Another user's tinySA also shows this, so it is obviously a systematic problem.
https://groups.io/g/tinysa/message/7071

![image](https://user-images.githubusercontent.com/12542359/201532996-f31d2540-0f24-41e3-b8e0-49ebf5c50e8f.png) ![image](https://user-images.githubusercontent.com/12542359/201532791-039b1d12-b39f-4e26-85c8-464570466381.png)

**Comment by DiSlord** [comment]
Here is NanoVNA V2 screenshot example (artefact also present)
![image](https://user-images.githubusercontent.com/28828/201701745-7b5ddaf1-5c63-42e8-8001-e5eb7a2f1b15.png)
Different hardware (CPU and it have different SPI module, different firmware)

If use st7789 (LiteVNA62) firmware (LCD part) fully equal no artefact
![image](https://user-images.githubusercontent.com/28828/201703169-7064e2e7-06a7-4c43-9ea7-bb84d1d9a501.png)
As can see no artefacts, so i think this LCD ili9341 driver hardware problem.

Artefact visible after made screenshot (read operation from LCD).

**Comment by Ho-Ro** [comment]
Thx for your update, please close unless you want to investigate further.
