### ISSUE TITLE
S11 impedance changed with V1.2?

### ISSUE THREAD

**Issue by errolt** [DiSlord/NanoVNA-D#43]
With V1.1, a 50 ohm load showed +-50ohm and impedance in the S11 SMITH line:
![VNA_000101_000000](https://user-images.githubusercontent.com/6266552/205251263-8f32fcac-8fc8-434d-8c40-6a8e06202a88.jpg)

But with V1.2 it seems to show some dimensionless value and angle?
![1_20](https://user-images.githubusercontent.com/6266552/205251390-afe42f92-5f4f-4bac-b20c-e3a91348c852.jpg)

This affects all my saved screen setups.

How do I switch back to restive + reactive display?

**Comment by Ho-Ro** [comment]
Go to menu `DISPLAY` / `TRACE` (select the smith trace) / `<-BACK` / `FORMAT S11 (REFL)` / `SMITH / R + L/C`

**Comment by errolt** [comment]
Wow. Thank you. I would never have figured out that flow.
