### ISSUE TITLE
make flash fails

### ISSUE THREAD

**Issue by n3xus1** [DiSlord/NanoVNA-D#49]
I receive this error when issuing make flash
 
% make flash
make: *** No rule to make target `build/build/H.bin', needed by `flash'.  Stop.

thanks,

**Comment by Ho-Ro** [comment]
See my comment(s):
https://github.com/DiSlord/NanoVNA-D/commit/c60f20a82a32aed8e10a2683fc4d1fe662682e94#r95702779

**Comment by n3xus1** [comment]
> See my comment(s):
> [c60f20a#r95702779](https://github.com/DiSlord/NanoVNA-D/commit/c60f20a82a32aed8e10a2683fc4d1fe662682e94#r95702779)
> [c60f20a#r95702904](https://github.com/DiSlord/NanoVNA-D/commit/c60f20a82a32aed8e10a2683fc4d1fe662682e94#r95702904)

I see your comments, so these changes need to be pushed still I take it.
thanks

**Comment by Ho-Ro** [comment]
> I see your comments, so these changes need to be pushed still I take it.

@n3xus1 you could create a local branch and fix it on your own until fixed by upstream.
