### ISSUE TITLE
NanoVNA-H - wrong text formatting of bottom line

### ISSUE THREAD

**Issue by Ho-Ro** [DiSlord/NanoVNA-D#52]
The rightmost element of the bottom line display is overwritten by middle element `IFBW:1000 101p` when BW >= 1000, it reads `TOP 900.000 000 MHz` instead of `STOP 900.000 000 MHz`, see attached screen shot (same for CENTER/SPAN -> `PAN `

![antenna_long](https://user-images.githubusercontent.com/12542359/212310405-02037b97-e42b-46b4-a743-052ab0b5a32a.png)

Firmware version 1.2.19

**Comment by DiSlord** [comment]
Add this fix, thanks
