### ISSUE TITLE
Data smooth option not saved

### ISSUE THREAD

**Issue by OneOfEleven** [DiSlord/NanoVNA-D#56]
Hello

Looks like you guys are still doing wonders, I've installed the latest firmware release (v1.2.20) into my NanoVNA-H4, all looks very nice !

I've not looked at the source code for some time now (life things) but was just wondering if the data smooth option is meant to be remembered or not across power up/downs. If it's not meant to be saved in the vna's non-volatile config settings then that's no problem and please cancel/delete this issue message, but if it is then it doesn't appear to be restored at next power on.

Anyway, amazing work as usual :)

**Comment by DiSlord** [comment]
Smoothing, slightly distorts measurements, I don’t think it should be done as a saved parameter, the user should understand the consequences of using it
And choose when he needs it (not on an ongoing basis)
