### ISSUE TITLE
unable to reprograme nanovna-h

### ISSUE THREAD

**Issue by bendelathouwer** [DiSlord/NanoVNA-D#59]
When I try to connect to the nanovna in the stm cube programmer, I get the error that  the device is under read protection(see included photo).
Does anyone know how to fix this?

Thanks in advance for the help!

![error](https://user-images.githubusercontent.com/6255058/234227870-3ebeca8b-5538-4e30-b1cb-ee9dbf13a048.PNG)

**Comment by kotaraka** [comment]
I have had this issue before, and it was resolved by using a different USB port - I was getting this error when NanoVNA was connected directly to the USB-C port of my laptop but when I used the regular USB port on the laptop's docking station the problem disappeared, and I was able to reprogram it. Looks like either port speed or something else related to the hardware was incompatible with the MCU when using the native USB-C ports.

**Comment by 4Nallen** [comment]
Use an older version of STM and it works
