### ISSUE TITLE
No indicator NanoVNA-H Battery

### ISSUE THREAD

**Issue by AxxiMator** [DiSlord/NanoVNA-D#62]
Hello. After updating the firmware on NanoVNA-H to version v1.2.20, I did not find an icon on the screen showing the battery charge. I also scrolled through the messages on the forum - there is also no battery icon in the screenshots.
Is this a bug or is it missing for some other reason?
Thanks in advance.

**Comment by DiSlord** [comment]
Need check D1 diode, +battery connected to MCU pin 1 (battery power) over D1

**Comment by AxxiMator** [comment]
In previous firmware - the battery was displayed. Disappeared after updating to version v1.2.20.
