### ISSUE TITLE
Cable length measurement v1.2.22

### ISSUE THREAD

**Issue by AxxiMator** [DiSlord/NanoVNA-D#63]
When measuring for a cable, it shows for a cable 10 times more than the real one. Velocity is set to 66%, with a real cable length of about 7 meters, the NanoVNA reading is about 70 meters.

**Comment by AxxiMator** [comment]
Так  на каком частотном промежутке измерят длину кабеля? 50-900 - одна длина, 50-800 другая. 
Непонятна фраза по мере увеличения длины уменьшайте верхнюю частоту - зачем и как определить, при каких значениях верхней частоты прибор показывает корректную длину кабеля?

**Comment by nlroth** [comment]
Refer to the user group.You can start with this msg thread: https://groups.io/g/nanovna-users/topic/77375866#26884
Do a search for TDR on the user group for more information.

    On Wednesday, May 17, 2023 at 01:50:32 p.m. EDT, Axxi ***@***.***> wrote:  
 
 


Так на каком частотном промежутке измерят длину кабеля? 50-900 - одна длина, 50-800 другая.
Непонятна фраза по мере увеличения длины уменьшайте верхнюю частоту - зачем и как определить, при каких значениях верхней частоты прибор показывает корректную длину кабеля?

**Comment by AxxiMator** [comment]
Thank you very much. I will study further.
