### ISSUE TITLE
Lower Start Frequency?

### ISSUE THREAD

**Issue by Moonman0922** [DiSlord/NanoVNA-D#66]
I was wondering if there was a way to further decrease the allowed starting frequency for sweeps. 800hz is worlds better than 50k for my purposes, but it would be nice to have the option to decrease that even further, maybe even to 1hz. I have no knowledge of what impacts that would have on accuracy, just wondering if it would be possible to do.

**Comment by DiSlord** [comment]
Limits in used generators
SI5351 allow only 800Hz Output
MS5351 allow 1.5k
Also on low frequency VNA perfomance very poor, and need use it very carefully. Additional IF (12kHz) harmonics noise damage measured data
