### ISSUE TITLE
Referance value when measuring S21 logMag

### ISSUE THREAD

**Issue by babak777** [DiSlord/NanoVNA-D#67]
I am testing several attenuators , and  like to set reference value for them so I can get better resolution with smaller scale per division.
It acts strange.

Display->Scale->Reference Position

NanoVNA H

Version:  1.2.20
LCD 320x240

**Comment by DiSlord** [comment]
You can use reference/scale settings, or use quick tap on screen:
![scale](https://github.com/DiSlord/NanoVNA-D/assets/28828/c4ee7c92-97ea-4317-bf84-577c26f070ef)
Ref+ move active trace up
Scale*2 zoom out active trace
Scale/2 zoom in active trace
Ref- move active trace down
