### ISSUE TITLE
Other ways to support you project

### ISSUE THREAD

**Issue by Sonic0** [DiSlord/NanoVNA-D#73]
Your PayPal link to support your project does not work anymore. Would you happen to have any other alternative?

**Comment by Ho-Ro** [comment]
Please check this possibility:
https://github.com/DiSlord/NanoVNA-D/blob/00e21dcdd3baf17074b3c82aabc9b21f52cbd4b6/main.c#L138

**Comment by Sonic0** [comment]
I'm sorry, but I'm not sure how to send money with WebMoney without registration. Have you considered using GitHub Sponsor (payments through GitHub) or Patreon?

**Comment by DiSlord** [comment]
At this moment difficult use any variants send money to Russia :)
PS anyway thanks

**Comment by Sonic0** [comment]
Yeah, everyone is familiar with the situation 😩. Thank you so much for your hard work!
