### ISSUE TITLE
Error in formatting display data for measure Xtal

### ISSUE THREAD

**Issue by Robyrob** [DiSlord/NanoVNA-D#78]
In displaing data for measure Series XTAL, there is an error in formatting line 4.
I think you forget to write yp+=STR_MEASURE_HEIGHT in file measure.c  function "draw_serial_result", line 446

**Comment by DiSlord** [comment]
Thanks, fixed in https://github.com/DiSlord/NanoVNA-D/commit/ed9d4fd92f4e92a7ffb8920e3ab68d35ff39df47
