### ISSUE TITLE
e-delay for s11, s21

### ISSUE THREAD

**Issue by owenduffy** [DiSlord/NanoVNA-D#80]
It is commonly the case that the appropriate value of e-delay is different for s11 and s21 measurements.

It would be really convenient if one could specify a s11 e-delay and s21 e-delay so that the presented data for a single sweep is correct for both s11 and s21 derived metrics.

Owen

**Comment by DiSlord** [comment]
Better add THRU calibration standard compensation (only additional delay) as in LiteVNA Calibration standard option.

PS NanoVNA-Saver allow add this on calibration as I remember (in calibration, Through, Offset delay)

**Comment by owenduffy** [comment]
> Better add THRU calibration standard compensation (only additional delay) as in LiteVNA Calibration standard option.
> 
> PS NanoVNA-Saver allow add this on calibration as I remember (in calibration, Through, Offset delay)

I am not sure that I understand you here.

If you mean deduction of the cable used to perform the THRU step of calibration during the calibration measurements so that the VNA is now calibrated with zero delay Port 1 to Port 2, that does not deal with the case that I described.

Consider a calibration with zero delay Port 1 to Port 2, and we connect the DUT with two  cables with propagation time 1ns and 3ns, the correct e-delay for s11 correction is 2ns (2* cable1) and for s21 correction is 4ns (cable1 + cable2).

Owen

**Comment by DiSlord** [comment]
Now possible input edelay for S11 and S21 traces
https://github.com/DiSlord/NanoVNA-D/commit/8d3ad9b76d1502a00e3737144a8dc87e2600adc4
You can build firmware or download it from beta test group
https://groups.io/g/nanovna-beta-test/message/4582

**Comment by owenduffy** [comment]
Thanks, that is very responsive.

I have applied for access and will test it ASAP.

Owen

**Comment by owenduffy** [comment]
Initial testing is good... more in the morning... Owen

**Comment by owenduffy** [comment]
I have done one practical test where the DUT was a A/B coax switch, test jig e-delay 3ns and 2.205ns. It worked as it should, s21 phase reconciles with physical path length, s11 looks good. I will write the test up in a blog article to show the usefulness of the facility.

I browsed the commit, there were a lot of small changes, and you achieved that very quickly, thanks for your fine effort, very well done.

Owen
