### ISSUE TITLE
Enhancement: capturetiff command

### ISSUE THREAD

**Issue by owenduffy** [DiSlord/NanoVNA-D#89]
capture commands executed over a slow / unreliable wireless link on the UART port have two shortcomings become apparent due to the speed and link reliability:
- screen dumps (307kB) are large and take a long time to transfer;
- errors may occur and go undetected.

A possible solution is to implement a "capturetiff" command which sends a lossless compressed TIFF image (as can already be written to SD).

Calculating a common CRC32 or CRC16 checksum and sending it after the capture data would allow the receiving appliction to flag data corruption in real time. Suggested format is:

CRC32: 0x01234
CH>

This solution is fully compatible with existing applications. An application could check for firmware support by executing a help command and scanning for "capturetiff", and if it exists, to use it in preference to "capture".

Owen

**Comment by DiSlord** [comment]
https://github.com/DiSlord/NanoVNA-D/commit/87427bf93c96d20abb5f3ff4420bb7ff8f2257b8
