### ISSUE TITLE
NanoVNA-H problem with latest release v1.2.29

### ISSUE THREAD

**Issue by vladin79** [DiSlord/NanoVNA-D#93]
I have flashed the latest firmware release v1.2.29 on my NanoVNA-H HW version 3.6.1_SM_ST, but the screen was rotated on 90 degrees and all messed up.

**Comment by DiSlord** [comment]
Use last release (added SM_ST hardware support)

**Comment by vladin79** [comment]
I can confirm that with the latest release 1.2.40 everything is working fine.
